model : D8
dataset : <PATH_TO_DATASET_.h5_FILE>

parameters :
  lr : 1.0e-2
  weight_decay : 1.0e-4
  test_size : 0.2
  batch_size : 128
  epochs : 100
  early_stopping : 15
  report_interval : 5
  lr_decay : 0.1
  step_size : 50
  milestones : [ 25, 50, 75 ]


save_dir : <PATH_TO_SAVE_DIR>