model : ResNet50
dataset : ../../../data/Galaxy10_DECals.h5

parameters :
  lr : 1.0e-3
  weight_decay : 1.0e-5
  momentum : 0.9
  test_size : 0.2
  batch_size : 128
  epochs : 100
  early_stopping : 5
  report_interval : 5
  lr_decay : 0.1


save_dir : ../../../save_dir/