model : ResNet18
dataset : 
  train: /home/pandya.sne/Galaxy10_DECals.h5
  test: /home/pandya.sne/random_rotations.hdf5

parameters :
  lr : 1.0e-2
  weight_decay : 1.0e-4
  momentum : 0.9
  test_size : 0.2
  batch_size : 128
  epochs : 100
  early_stopping : 5
  report_interval : 5
  lr_decay : 0.1
  step_size : 50
  milestones : [ 50, 75 ]


save_dir : ../../../save_dir/