model : WRN28_10_d8d4d1
dataset : /n/holystore01/LABS/iaifi_lab/Users/spandya/data/Galaxy10_DECals.h5

parameters :
  lr : 1.0e-2
  weight_decay : 1.0e-4
  momentum : 0.9
  test_size : 0.2
  batch_size : 128
  epochs : 100
  early_stopping : 15
  report_interval : 5
  lr_decay : 0.1
  step_size : 50
  milestones : [ 25, 50, 75 ]


save_dir : /n/home04/spandya/final_models/